	/* CRIANDO O DB E AS TABLES */	
	CREATE DATABASE ACADEMIA
	GO

	USE ACADEMIA
	GO

	CREATE TABLE ENDERECO(
		COD_ENDERECO SMALLINT CONSTRAINT PK_ENDERECO PRIMARY KEY IDENTITY,
		RUA VARCHAR(50) NOT NULL,
		NUMERO VARCHAR(5) NOT NULL,
		COMPLEMENTO VARCHAR(50),
		BAIRRO VARCHAR(30) NOT NULL,
		CIDADE VARCHAR(50) NOT NULL,
		ESTADO CHAR(2) NOT NULL
	)
	GO

	CREATE TABLE PESSOA(
		CPF CHAR(14) CONSTRAINT PK_PESSOA PRIMARY KEY,
		NOME VARCHAR(50) NOT NULL, 
		DT_NASC DATE NOT NULL,
		RG VARCHAR(15) NOT NULL,
		SENHA VARCHAR(20) NOT NULL,
		RESPONSAVEL BIT,
		COD_ENDERECO SMALLINT
		CONSTRAINT FK_PESSOA_ENDERECO
		FOREIGN KEY(COD_ENDERECO)
		REFERENCES ENDERECO(COD_ENDERECO)
	)
	GO

	CREATE TABLE TELEFONE(
		COD_TELEFONE SMALLINT CONSTRAINT PK_TELEFONE_ACADEMIA PRIMARY KEY IDENTITY,
		NUMERO CHAR(15) NOT NULL,
		CPF_PESSOA CHAR(14) NOT NULL,
		CONSTRAINT FK_TELEFONE_PESSOA
		FOREIGN KEY(CPF_PESSOA)
		REFERENCES PESSOA(CPF)
	)
	GO

	CREATE TABLE INSTRUTOR(
		COD_INSTRUTOR SMALLINT CONSTRAINT PK_INSTRUTOR_ACADEMIA PRIMARY KEY IDENTITY,
		TITULO VARCHAR(50) NOT NULL,
		STATUS_INSTRUTOR VARCHAR(15) NOT NULL,
		DATA_AD DATE NOT NULL,
		DATA_DE DATE,
		SALARIO MONEY NOT NULL,
		CPF_PESSOA CHAR(14) NOT NULL,
		CONSTRAINT UQ_INSTRUTOR_PESSOA
		UNIQUE(CPF_PESSOA),
		CONSTRAINT FK_INSTRUTOR_PESSOA
		FOREIGN KEY(CPF_PESSOA)
		REFERENCES PESSOA(CPF)
	)
	GO

	CREATE TABLE PACOTE(
		COD_PACOTE SMALLINT CONSTRAINT PK_PACOTE_ACADEMIA PRIMARY KEY IDENTITY,
		VALOR SMALLMONEY NOT NULL,
		TIPO_PAC VARCHAR(20) NOT NULL,
		DESCRICAO VARCHAR(100) NOT NULL,
		DT_INICIAL_PAC DATE NOT NULL,
		DT_FINAL_PAC DATE NOT NULL
	)
	GO

	CREATE TABLE ALUNO(
		MATRICULA SMALLINT CONSTRAINT PK_ALUNO_ACADEMIA PRIMARY KEY IDENTITY(1000,1),
		DT_MATRICULA DATE NOT NULL,
		ALTURA DECIMAL(3,2) NOT NULL,
		PESO DECIMAL(5,2) NOT NULL,
		STATUS_ALUNO BIT NOT NULL,
		CPF_PESSOA CHAR(14) NOT NULL,
		CONSTRAINT UQ_ALUNO_PESSOA
		UNIQUE(CPF_PESSOA),
		CONSTRAINT FK_ALUNO_PESSOA
		FOREIGN KEY(CPF_PESSOA)
		REFERENCES PESSOA(CPF),
		COD_PACOTE SMALLINT NOT NULL,
		CONSTRAINT FK_ALUNO_PACOTE
		FOREIGN KEY(COD_PACOTE)
		REFERENCES PACOTE(COD_PACOTE)
	)
	GO

	CREATE TABLE ATIVIDADE(
		COD_ATIVIDADE SMALLINT CONSTRAINT PK_ATIVIDADE_ACADEMIA PRIMARY KEY IDENTITY,
		DESCRICAO VARCHAR(20) NOT NULL,
		STATUS_ATIVIDADE BIT NOT NULL
	)
	GO

	CREATE TABLE TURMA(
		COD_TURMA SMALLINT CONSTRAINT PK_TURMA_ACADEMIA PRIMARY KEY IDENTITY,
		QNT_ALUNO SMALLINT NOT NULL,
		HORARIO TIME(0) NOT NULL,
		DT_INICIAL DATE NOT NULL,
		DT_FINAL DATE NOT NULL,
		TIPO_TURMA VARCHAR(8) NOT NULL,
		CONSTRAINT CK_TURMA_TIPO 
		CHECK(TIPO_TURMA IN('infantil', 'jovem', 'idoso')), 
		STATUS_TURMA BIT NOT NULL, -- 
		COD_ATIVIDADE SMALLINT NOT NULL,
		CONSTRAINT FK_TURMA_ATIVIDADE
		FOREIGN KEY(COD_ATIVIDADE)
		REFERENCES ATIVIDADE(COD_ATIVIDADE),
		COD_INSTRUTOR SMALLINT NOT NULL,
		CONSTRAINT FK_TURMA_INSTRUTOR
		FOREIGN KEY (COD_INSTRUTOR)
		REFERENCES INSTRUTOR(COD_INSTRUTOR),
		MATRICULA SMALLINT,
		CONSTRAINT FK_TURMA_ALUNO
		FOREIGN KEY (MATRICULA)
		REFERENCES ALUNO(MATRICULA)
	)
	GO

	CREATE TABLE ALUNO_TURMA(
		COD_ALUNO_TURMA SMALLINT CONSTRAINT PK_ALUNO_TURMA_ACADEMIA PRIMARY KEY IDENTITY,
		MATRICULA SMALLINT NOT NULL,
		CONSTRAINT FK_ALUNO_TURMA_ALUNO
		FOREIGN KEY (MATRICULA)
		REFERENCES ALUNO(MATRICULA),
		COD_TURMA SMALLINT NOT NULL,
		CONSTRAINT FK_ALUNO_TURMA_TURMA
		FOREIGN KEY (COD_TURMA)
		REFERENCES TURMA(COD_TURMA)
	)
	GO

	CREATE TABLE FREQUENCIA(
		COD_FREQUENCIA SMALLINT CONSTRAINT PK_FREQUENCIA_ACADEMIA PRIMARY KEY IDENTITY,
		DT_FALTA DATE NOT NULL,
		MOTIVO VARCHAR(100),
		COD_ALUNO_TURMA SMALLINT NOT NULL,
		CONSTRAINT FK_FREQUENCIA_ALUNO_TURMA
		FOREIGN KEY (COD_ALUNO_TURMA)
		REFERENCES ALUNO_TURMA(COD_ALUNO_TURMA)
	)
	GO
